export const authActionTypes = {
    LOGIN_WAITING: 'LOGIN_WAITING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_WAITING: 'LOGOUT_WAITING',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
};

export const projectsActionTypes = {
    PROJECTS_LOADING: 'PROJECT_LOADING',
    PROJECTS_LOADED: 'PROJECTS_LOADED',
    PROJECTS_LOAD_FAIL: 'PROJECTS_LOAD_FAIL',
    PROJECTS_ADD_WAITING: 'PROJECTS_ADD_WAITING',
    PROJECTS_ADD_SUCCESS: 'PROJECTS_ADD_SUCCESS',
    PROJECTS_ADD_FAIL: 'PROJECTS_ADD_FAIL',
    PROJECTS_DEL_WAITING: 'PROJECTS_DEL_WAITING',
    PROJECTS_DEL_SUCCESS: 'PROJECTS_DEL_SUCCESS',
    PROJECTS_DEL_FAIL: 'PROJECTS_DEL_FAIL',
    PROJECTS_UPDATE_WAITING: 'PROJECTS_UPDATE_WAITING',
    PROJECTS_UPDATE_SUCCESS: 'PROJECTS_UPDATE_SUCCESS',
    PROJECTS_UPDATE_FAIL: 'PROJECTS_UPDATE_FAIL',
};

export const tasksActionTypes = {
    TASKS_LOADING: 'TASKS_LOADING',
    TASKS_LOADED: 'TASKS_LOADED',
    TASKS_LOAD_FAIL: 'TASKS_LOAD_FAIL',
    TASKS_ADD_WAITING: 'TASKS_ADD_WAITING',
    TASKS_ADD_SUCCESS: 'TASKS_ADD_SUCCESS',
    TASKS_ADD_FAIL: 'TASKS_ADD_FAIL',
    TASKS_DEL_WAITING: 'TASKS_DEL_WAITING',
    TASKS_DEL_SUCCESS: 'TASKS_DEL_SUCCESS',
    TASKS_DEL_FAIL: 'TASKS_DEL_FAIL',
    TASKS_UPDATE_WAITING: 'TASKS_UPDATE_WAITING',
    TASKS_UPDATE_SUCCESS: 'TASKS_UPDATE_SUCCESS',
    TASKS_UPDATE_FAIL: 'TASKS_UPDATE_FAIL',
};